openapi: 3.0.4
info:
  title: Payment Gateway API
  version: v1.0.0.0
paths:
  '/payments/{id}':
    get:
      tags:
        - Payments
      summary: 'Gets a previously submitted payment, by unique ID'
      operationId: GetPaymentById
      parameters:
        - name: id
          in: path
          description: 'A unique ID, provided by this service'
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PaymentDto'
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentDto'
            text/json:
              schema:
                $ref: '#/components/schemas/PaymentDto'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /payments:
    post:
      tags:
        - Payments
      summary: Creates a new payment
      operationId: CreatePayment
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PaymentDto'
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentDto'
            text/json:
              schema:
                $ref: '#/components/schemas/PaymentDto'
        '422':
          description: Unprocessable Content
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
components:
  schemas:
    CreatePaymentRequest:
      required:
        - amount
        - cardNumber
        - currency
        - cvv
        - expiryMonth
        - expiryYear
      type: object
      properties:
        cardNumber:
          maxLength: 19
          minLength: 14
          type: string
          description: Credit Card number containing 14 to 19 numeric characters only
        expiryMonth:
          maximum: 12
          minimum: 1
          type: integer
          description: 'Expiration month, from 1 to 12. Combined with PaymentGateway.Api.Contracts.CreatePaymentRequest.ExpiryYear, this must be a date in the future.'
          format: int32
        expiryYear:
          type: integer
          description: 'Expiration year, four digits. Combined with PaymentGateway.Api.Contracts.CreatePaymentRequest.ExpiryMonth, thus must be a date in the future.'
          format: int32
        currency:
          maxLength: 3
          minLength: 3
          type: string
          description: Three character ISO currency code as specified by ISO-4217 for a country supported by this service.
        amount:
          type: integer
          description: The payment amount in minor currency units.
          format: int32
        cvv:
          maxLength: 4
          minLength: 3
          type: string
          description: Card security code containing 3 to 4 numeric characters only
      additionalProperties: false
    PaymentDto:
      required:
        - amount
        - cardNumberLastFour
        - currency
        - expiryMonth
        - expiryYear
        - paymentId
        - status
      type: object
      properties:
        paymentId:
          type: string
          description: Unique identifier of this payment attempt
          format: uuid
        status:
          $ref: '#/components/schemas/PaymentStatusDto'
        cardNumberLastFour:
          type: integer
          format: int32
        expiryMonth:
          maximum: 12
          minimum: 1
          type: integer
          format: int32
        expiryYear:
          type: integer
          format: int32
        currency:
          maxLength: 3
          minLength: 3
          type: string
        amount:
          type: integer
          format: int32
      additionalProperties: false
      description: Represents a payment that has already been attempted
    PaymentStatusDto:
      enum:
        - Authorized
        - Declined
      type: string
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }
    ValidationProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          nullable: true
      additionalProperties: { }